version: '3.8'

services:
  infra-deployment-api:
    build: .
    container_name: infra-deployment-api
    ports:
      - "8000:8000"
    volumes:
      # Mount Docker socket to allow container to manage Docker
      - /var/run/docker.sock:/var/run/docker.sock
      # Mount current directory for compose files
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - FLASK_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - infra-api-network

networks:
  infra-api-network:
    driver: bridge